CAPTURE_AGENT_NAME: PyCA-test
IGNORE_TZ: False
ADMIN_SERVER:
  URL: http://172.22.28.161:8080
  USER: matterhorn_system_account
  PASSWD: CHANGE_ME
UPDATE_FREQUENCY: 60
CAPTURE_PIPES:
  -
    flavor: audience/source
    suffix: mpg
    preview: False
    launch: v4l2src device=/dev/video0 ! queue ! video/x-raw-rgb ! ffmpegcolorspace ! ffenc_mpeg2video bitrate=2000000 ! mpegtsmux ! filesink location=%(file)s
  -
    flavor: presentation/source
    suffix: mpg
    preview: True
    launch: >
         v4l2src device=/dev/video1 ! tee name=x ! queue !
         video/x-raw-rgb,framerate=30/1 ! ffmpegcolorspace ! ffenc_mpeg2video bitrate=2000000 ! mpegtsmux ! filesink location=%(file)s
         x. ! queue ! videorate max-rate=1 ! jpegenc ! multifilesink location=%(preview)s
  -
    flavor: presenter/source
    suffix: mpg
    preview: True
    launch: hdv1394src blocksize="4136" ! tee name=x ! queue ! filesink location=%(file)s x. ! queue ! tsdemux ! mpeg2dec ! videorate max-rate=1 ! jpegenc ! multifilesink location=%(preview)s
  -
    flavor: audience/source
    suffix: mp3
    preview: True
    launch: >
         alsasrc device=hw:0 ! tee name=x ! queue ! audioconvert ! lamemp3enc ! id3v2mux ! filesink location=%(file)s
         x.! queue ! audioconvert ! spectrascope ! videorate max-rate=1 ! jpegenc ! multifilesink location=%(preview)s
UI:
  USER: admin
  PASSWD: opencast
  REFRESH_RATE: 2
  URI: http://localhost:5000
